problem_copying_the_lesson: 'There was a problem copying the lesson'
lesson_already_copied: 'You already have a copy of this lesson'
already_published_lesson: 'The lesson you selected has already been published'
problem_publishing_lesson: 'There was a problem publishing the lesson'
