# TAGS
min_tag_length: 1
max_tag_length: 25
min_tags_for_item: 4
# ADMIN USER
admin_email: 'nanjing@china.gov'
# APPLICATION LANGUAGE
application_language: 'en'
# DIALOGS
seconds_for_timeout_dialogs: 2500
# DASHBOARD PAGINATION
lessons_for_page_in_dashboard: 5
lesson_pages_in_dashboard: 3
media_elements_for_page_in_dashboard: 13
media_element_pages_in_dashboard: 3
# LESSONS PAGINATTION EVERYWHERE OUT OF DASHBOARD
compact_lesson_pagination: 18
# MEDIA ELEMENT PAGINATION EVERYWHERE OUT OF DASHBOARD
compact_media_element_pagination: 18
compact_media_element_pagination_options: [18, 27, 36]
expanded_media_element_pagination: 14
expanded_media_element_pagination_options: [14, 21, 28]
# NOTIFICATIONS
notifications_loaded_together: 8
# VIRTUAL CLASSROOM
lessons_for_page_in_virtual_classroom: 10
lessons_in_playlist: 20
lessons_in_quick_loader: 18
# LESSON EDITOR
images_for_page_in_gallery: 56
videos_for_page_in_gallery: 18
audios_for_page_in_gallery: 18
# APP COLORS
colors:
  red: '#B51726' # colore sfondo della componente 'testo' nella timeline nel psd dell'editor video
  green: '#41A62A' # colore elementi didattici
  light_green: '#95E195' # scelto da me
  orange: '#F29400' # colore lezioni
  blue: '#2807CE' # scelto da me
  light_blue: '#2EAADC' # colore virtual classroom
  white: '#F2F2F2' # scelto da me
  black: '#373737' # colore dell'header desy
  gray: '#7D7D7D' # scritta 'profile' nel menu quando è selezionata (non sfondo)
  purple: '#6A05AE' # scelto da me
  yellow: '#FDB525' # sfondo sezione 'what is DESY'
  brown: '#622F0B' # scelto da me
  pink: '#F4D0F3' # scelto da me
