# TAGS
min_tag_length: 3
max_tag_length: 20
min_tags_for_item: 4
force_min_tags_for_item: false
# ADMIN USER
admin_email: 'nanjing@china.gov'
# APPLICATION LANGUAGE
application_language: 'en'
# DASHBOARD PAGINATION
lessons_for_page_in_dashboard: 5
lesson_pages_in_dashboard: 3
media_elements_for_page_in_dashboard: 7
media_element_pages_in_dashboard: 3
# LESSONS PAGINATTION EVERYWHERE OUT OF DASHBOARD
compact_lesson_pagination: 18
# MEDIA ELEMENT PAGINATION EVERYWHERE OUT OF DASHBOARD
compact_media_element_pagination: 18
compact_media_element_pagination_options: [18, 27, 36]
expanded_media_element_pagination: 12
expanded_media_element_pagination_options: [12, 16, 24]
# NOTIFICATIONS
notifications_loaded_together: 10
