# SEEDS
locations: ['Shanghai', 'Guangzhou', 'Wuhan', 'Beijing', 'Tianjin', 'Shenzhen', 'Nanjing'] # possibly, link here an external file with the list of locations
subjects: ['Mathematics', 'Natural Sciences', 'Geography', 'History', 'Visive Arts', 'Music', 'Phisycal Education', 'Computer Science', 'Languages', 'Literature', 'Chemistry']
school_levels: ['Primary School', 'Secondary School', 'Undergraduate']
admin_username: 'DESY Admin User'
admin_email: 'desy@morganspa.com'
# TAGS
min_tag_length: 1
max_tag_length: 25
min_tags_for_item: 4
# APPLICATION LANGUAGE
application_language: 'en'
# TIMES
seconds_for_timeout_dialogs: 2500
seconds_for_saving_cache: 5000 # deve essere 120000 ?
# DASHBOARD PAGINATION
lessons_for_page_in_dashboard: 5
lesson_pages_in_dashboard: 3
media_elements_for_page_in_dashboard: 13
media_element_pages_in_dashboard: 3
# LESSONS PAGINATTION EVERYWHERE OUT OF DASHBOARD
compact_lesson_pagination: 18
# MEDIA ELEMENT PAGINATION EVERYWHERE OUT OF DASHBOARD
compact_media_element_pagination: 18
compact_media_element_pagination_options: [18, 27, 36]
expanded_media_element_pagination: 14
expanded_media_element_pagination_options: [14, 21, 28]
# NOTIFICATIONS
notifications_loaded_together: 8
# VIRTUAL CLASSROOM
lessons_for_page_in_virtual_classroom: 10
lessons_in_playlist: 20
lessons_in_quick_loader: 18
# GALLERIES
images_for_page_in_gallery: 42
videos_for_page_in_gallery: 18
audios_for_page_in_gallery: 12
# APP COLORS
colors:
  red:
    pos: 3
    code: '#B51726'
  green:
    pos: 6
    code: '#41A62A'
  orange:
    pos: 4
    code: '#F29400'
  light_blue:
    pos: 5
    code: '#2EAADC'
  white:
    pos: 2
    code: '#F2F2F2'
  black:
    pos: 1
    code: '#373737'
