min_tag_length: 3 # warning: changing this value you might have to update tag_test.rb
max_tag_length: 20 # warning: changing this value you might have to update tag_test.rb
admin_email: 'nanjing@china.gov'
application_language: 'en'
min_tags_for_item: 4
force_min_tags_for_item: false
lessons_for_page_in_dashboard: 5
lesson_pages_in_dashboard: 3
media_elements_for_page_in_dashboard: 7
media_element_pages_in_dashboard: 3
compact_lesson_pagination: 18
compact_media_element_pagination: 18
compact_media_element_pagination_options: [18, 27, 36]
expanded_media_element_pagination: 12
expanded_media_element_pagination_options: [12, 16, 24]
