# TAGS
min_tag_length: 1
max_tag_length: 25
min_tags_for_item: 4
# ADMIN USER
admin_email: 'nanjing@china.gov'
# APPLICATION LANGUAGE
application_language: 'en'
# DIALOGS
seconds_for_timeout_dialogs: 2500
# DASHBOARD PAGINATION
lessons_for_page_in_dashboard: 5
lesson_pages_in_dashboard: 3
media_elements_for_page_in_dashboard: 13
media_element_pages_in_dashboard: 3
# LESSONS PAGINATTION EVERYWHERE OUT OF DASHBOARD
compact_lesson_pagination: 18
# MEDIA ELEMENT PAGINATION EVERYWHERE OUT OF DASHBOARD
compact_media_element_pagination: 18
compact_media_element_pagination_options: [18, 27, 36]
expanded_media_element_pagination: 14
expanded_media_element_pagination_options: [14, 21, 28]
# NOTIFICATIONS
notifications_loaded_together: 8
# VIRTUAL CLASSROOM
lessons_for_page_in_virtual_classroom: 12
playlist_lessons_loaded_together: 10
